### ISSUE TITLE
Razer Viper Mini SE dongle not recognized; no 8kHz option

### ISSUE THREAD

**Issue by Hyydro** [philipbry/RazerAutoPollingRate#1]
The title basically says it all. I followed the instructions on the main page and given the application's simple layout, I'm relatively confident I didn't mess anything up. The taskbar icon shows a red bar and the message "Searching for dongle" when hovering over it.
![image](https://github.com/philipbry/RazerAutoPollingRate/assets/107633948/bfac6960-8b6c-490d-aa25-67e57ac0a4ac)

**Comment by philipbry** [comment]
could you download this updated version and follow these steps:
[razerautopollingrate-1.1.1_Setup.zip](https://cdn.discordapp.com/attachments/879900148489146418/1164635395808567389/razerautopollingrate-1.1.1_Setup.zip)

- install
- right click the tray icon and quit
- navigate %LocalAppData%\razerautopollingrate\app-1.1.1\
- right click and open a cmd window here
- enter .\razerautopollingrate.exe and press enter
- let it run for 5 seconds, copy the output in the console and paste it here

**Comment by Hyydro** [comment]
```
AppData\Local\razerautopollingrate\app-1.1.1\razerautopollingrate.exe
159 name: Razer Viper Mini Signature Editionvendor:  5426
NamedError [NotFoundError]: Failed to execute 'requestDevice' on 'USB': No device selected.
    at WebUSB.requestDevice (C:\Users\schop\AppData\Local\razerautopollingrate\app-1.1.1\resources\app\node_modules\usb\dist\webusb\index.js:163:19)
    at async get_dongle (C:\Users\schop\AppData\Local\razerautopollingrate\app-1.1.1\resources\app\src\main.js:166:20)
    at async check_polling_rate (C:\Users\schop\AppData\Local\razerautopollingrate\app-1.1.1\resources\app\src\main.js:318:24)
159 name: Razer Viper Mini Signature Editionvendor:  5426
NamedError [NotFoundError]: Failed to execute 'requestDevice' on 'USB': No device selected.
    at WebUSB.requestDevice (C:\Users\schop\AppData\Local\razerautopollingrate\app-1.1.1\resources\app\node_modules\usb\dist\webusb\index.js:163:19)
    at async get_dongle (C:\Users\schop\AppData\Local\razerautopollingrate\app-1.1.1\resources\app\src\main.js:166:20)
    at async check_polling_rate (C:\Users\schop\AppData\Local\razerautopollingrate\app-1.1.1\resources\app\src\main.js:318:24)
159 name: Razer Viper Mini Signature Editionvendor:  5426
NamedError [NotFoundError]: Failed to execute 'requestDevice' on 'USB': No device selected.
    at WebUSB.requestDevice (C:\Users\schop\AppData\Local\razerautopollingrate\app-1.1.1\resources\app\node_modules\usb\dist\webusb\index.js:163:19)
    at async get_dongle (C:\Users\schop\AppData\Local\razerautopollingrate\app-1.1.1\resources\app\src\main.js:166:20)
    at async check_polling_rate (C:\Users\schop\AppData\Local\razerautopollingrate\app-1.1.1\resources\app\src\main.js:318:24)
159 name: Razer Viper Mini Signature Editionvendor:  5426
NamedError [NotFoundError]: Failed to execute 'requestDevice' on 'USB': No device selected.
    at WebUSB.requestDevice (C:\Users\schop\AppData\Local\razerautopollingrate\app-1.1.1\resources\app\node_modules\usb\dist\webusb\index.js:163:19)
    at async get_dongle (C:\Users\schop\AppData\Local\razerautopollingrate\app-1.1.1\resources\app\src\main.js:166:20)
    at async check_polling_rate (C:\Users\schop\AppData\Local\razerautopollingrate\app-1.1.1\resources\app\src\main.js:318:24)
```

**Comment by philipbry** [comment]
Should be fixed now.
